name: 'Setup hledger'
description: 'Download and install hledger binary'
branding:
  icon: 'dollar-sign'
  color: 'yellow'
inputs:
  version:
    description: 'Version to install.'
    required: true
    default: '1.27'
outputs:
  version:
    description: "Installed version."
    value: ${{ steps.install.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: install
      shell: bash
      run: |
        ${{ github.action_path }}/src/install.sh --version "${{ inputs.version }}" --dist "$HOME/.local/bin"
        echo "version=$($HOME/.local/bin/hledger --version)" >> $GITHUB_OUTPUT
        echo "$HOME/.local/bin" >> $GITHUB_PATH
